CREATE TABLE all_2509.cross_join (
	id int4 NULL,
	purchase_date timestamptz NULL,
	ddmmyyyy date NULL,
	"time" varchar(20) NULL,
	quarter varchar(20) NULL,
	qtr int4 NULL,
	"year" int4 NULL,
	"month" int4 NULL,
	day_of_month int4 NULL,
	is_special_day bool NULL,
	is_online_sale_offers bool NULL,
	day_of_week int4 NULL,
	is_weekend bool NULL,
	is_morning bool NULL,
	is_afternoon bool NULL,
	is_evening bool NULL,
	is_night bool NULL,
	is_female bool NULL,
	customer_id varchar(50) NULL,
	gender varchar(50) NULL,
	product_name varchar(255) NULL,
	item_status varchar(50) NULL,
	quantity int4 NULL,
	currency varchar(10) NULL,
	item_price numeric(10, 2) NULL,
	shipping_price numeric(10, 2) NULL,
	ship_city varchar(100) NULL,
	ship_state varchar(100) NULL,
	ship_postal_code int4 NULL,
	category varchar(100) NULL,
	total_amount numeric(12, 2) NULL,
	author varchar(255) NULL,
	"publication" varchar(255) NULL,
	profit_percentage numeric(5, 2) NULL,
	profit_inr numeric(12, 2) NULL,
	cost_price numeric(12, 2) NULL
);
