CREATE TABLE all_2509.cross_join_temp (
    id int4 NULL,
    "Purchase-date" varchar(50) NULL,
    "Date" varchar(50) NULL,
    "Time" varchar(50) NULL,
    quarter varchar(50) NULL,
    qtr int4 NULL,
    "Year" int4 NULL,
    "Month" int4 NULL,
    date_1 int4 NULL,
    "Special Day" int4 NULL,
    "Online Sale Offers " int4 NULL,
    "Day" int4 NULL,
    weekend int4 NULL,
    morning int4 NULL,
    afternoon int4 NULL,
    evening int4 NULL,
    night int4 NULL,
    gender int4 NULL,
    "Customer ID" varchar(50) NULL,
    "Gender
F=1665
M=1815" varchar(50) NULL,
    "Product-Name" varchar(512) NULL,
    "Item-Status" varchar(50) NULL,
    quantity int4 NULL,
    currency varchar(50) NULL,
    "Item Price" int4 NULL,
    "Shipping-Price" int4 NULL,
    "Ship-City" varchar(50) NULL,
    "Ship-State" varchar(50) NULL,
    "Ship-Postal-Code" int4 NULL,
    category varchar(50) NULL,
    "Total_
amount" int4 NULL,
    "Author " varchar(512) NULL,
    "Publication" varchar(512) NULL,
    "Profit Percentage
 (%)" int4 NULL,
    "Profit (INR)" float4 NULL,
    "Cost Price" float4 NULL
);